project:
  type: website
  output-dir: docs

website:
  title: "Nitheshnirmal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Publication
      - href: publication.qmd  
      
format:
  html:
    theme: 
      light: journal
      dark: journal
    css: styles.css
    toc: true

editor: visual

