project:
  type: website
  output-dir: docs

website:
  title: "Nithesh"
  site-url: 'https://nitheshnirmal.github.io'
  site-path: '/'
  google-analytics: 
    tracking-id: "G-WPPJJR0N52"
    anonymize-ip: true
  page-navigation: true
  page-footer: 
    center: "copyright 2023"
    right: "Nitheshnirmal Sadhasivam"
  navbar:
    foreground: light
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: publication.qmd
        text: Publication
      - href: Blog.qmd
        text: Blog
        
        




      
format:
  html:
    page-layout: full
    theme: 
      light: journal
      dark: journal
    css: styles.css
    toc: true

editor: visual

