project:
  type: website
  output-dir: docs

website:
  title: "Nitheshnirmal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
format:
  html:
    theme: 
      light: journal
      dark: lux
    css: styles.css
    toc: true

editor: visual

