project:
  type: website
  output-dir: docs

website:
  title: "Nitheshnirmal.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Publications.qmd

format:
  html:
    theme: 
      light: vapor
      dark: cyborg
    css: styles.css
    toc: true

editor: visual

