---
title: ""
---

::: past-highlight
## What's old

-   Co-authored work focusing on 2023 Libya Dam Collapse published in **npj Natural Hazards** ([link](https://www.nature.com/articles/s44304-024-00056-1)).
-   Recipient of William A. Fischer Memorial Scholarship from the **American Society of Photogrammetry and Remote Sensing (ASPRS)** on January 2025.
-   I am part of a **UN report** led by Dr. Manoochehr Shirzaei detailing the asset damage based on synthetic aperture radar (SAR) data during the recent Hurricane Helene, which hit east coast of USA. [Incident Brief Report](https://collections.unu.edu/eserv/UNU:10021/UNU-INWEH_IncidentBrief_Hurricane-Helene_Nov-2024.pdf), [Press Release](https://unu.edu/inweh/news/hurricane-helene-posed-threat-over-31000-properties-us-combined-value-exceeding-125).
-   I presented my talk on October 23, 2025 about my work on California's Central Valley groundwater recharge during wet year 2023 in Geological Society of America Connects 25.
-   I presented a poster on May 18, 2025 about my work on California's Central Valley groundwater recharge during wet year 2023 in 2025 USGIF GEOINT Symposium.
-   Co-authored abstract got accepted for the 2025 EGU session NH6.2 – SAR remote sensing for natural and human-induced hazard applications (updates on this soon)**.**
-   **Sadhasivam, N.**, Werth, S., Carlson, G., Shirzaei, M. (9 December 2024). From Dry to Wet: Are Deep Central Valley Aquifers Recharged Following the Very Wet 2023? AGU Fall Meeting 2024, Washington D.C.
-   I presented my research work on Central Valley of California as a talk in the 2024 GRACE/GRACE-FO Science Team Meeting.
-   I presented my research work on assessing infrasturcture vulnerability in a populated Himalayan slope as a poster presentation in the 2024 Geological Society of America meeting ([Link to abstract](https://gsa.confex.com/gsa/2024AM/webprogram/Paper404507.html)).
-   I co-presented our team project on estimating water footpint of a reservoir in the Transboundary US-Mexico Region ([link](#0)) along with another team member from 2023 NSF I-GUIDE summer school on December 4, 2024 (note: recordings will be available soon online).
-   I got a best graduate poster award at **the Virginia Tech Office for GIS and Remote Sensing Research 2024 Symposium.**
-   I presented my study on building damage risk in Indian megacities from land subsidence at AGU Fall Meeting 2023, San Francisco, CA.
:::
