---
title: "Research articles (peer reviewed)"
title-block-banner: false
---

## Selected publications

::: {#2024}
1.  Ohenhen, LO, Zhai, G, Lucy, J, Werth, S, Carlson, G, Khorrami, M, Onyike, F, **Sadhasivam, N**, Tiwari, A, Ghobadi-Far, K and Sherpa, SF, 2025. Land subsidence risk to infrastructure in US metropolises. *Nature Cities*, pp.1-12. <https://doi.org/10.1038/s44284-025-00240-y>

2.  Shirzaei, M, Vahedifard, F, **Sadhasivam, N**, Ohenhen, L, Dasho, O, Tiwari, A, ... & AghaKouchak, A. (2025). Aging dams, political instability, poor human decisions and climate change: recipe for human disaster. *npj Natural Hazards*, *2*(1), 5. <https://doi.org/10.1038/s44304-024-00056-1>

3.  Shirzaei, M, **Sadhasivam, N**, Werth, S, Lucy, J, Etzler, W, Matin, M, Madani, K (2024). Helene Disaster: The Threat of Poor Management and Climate Change to Human Lives and Assets, United Nations University Institute for Water, Environment and Health (UNU-INWEH), Richmond Hill, Ontario, Canada, doi: 10.53328/INR24MSIR001. ([link](https://collections.unu.edu/eserv/UNU:10021/UNU-INWEH_IncidentBrief_Hurricane-Helene_Nov-2024.pdf))

4.  **Sadhasivam, N**, Chang, L, Tanyas, H (2024). An integrated approach for mapping slow-moving hillslopes and characterizing their activity using InSAR, slope units and a novel 2-D deformation scheme. *Nat Hazards* **120**, 3919–3941. DOI: <https://doi.org/10.1007/s11069-023-06353-8>

5.  Ahmad SM, **Sadhasivam N**, Lisa M, Lombardo L, Emil MK, Fadel I, van Westen CJ, Ahmed A. & Tanyas H (2022) Standing on the shoulder of a giant landslide: A six-year long InSAR look at a slow-moving hillslope in the western Karakoram. Geomorphology, 444, 108959. DOI: <https://doi.org/10.1016/j.geomorph.2023.108959>

6.  He K, Lombardo L, Chang L, **Sadhasivam N**, Hu X, Fang Z, & Tanyas H (2022) Investigating earthquake legacy effect on hillslope deformation using InSAR-derived time series. Earth Surface Processes and Landforms. DOI: <https://onlinelibrary.wiley.com/doi/epdf/10.1002/esp.5746>

7.  Panahi M, **Sadhasivam N**, Pourghasemi HR, Rezaie F & Lee S (2020) Spatial prediction of groundwater potential mapping based on convolutional neural network (CNN) and support vector regression (SVR). Journal of Hydrology, 588, p.125033. DOI: <https://doi.org/10.1016/j.jhydrol.2020.125033>
:::

## 
