---
title: "Publications"
---

## 2023

::: {#2023}
1.  Ahmad SM, **Sadhasivam N**, Lisa M, Lombardo L, Emil MK, Fadel I, van Westen CJ, Ahmed A. & Tanyas H (2022) Standing on the shoulder of a giant landslide: A six-year long InSAR look at a slow-moving hillslope in the western Karakoram. Geomorphology, 444, 108959. DOI: <https://doi.org/10.1016/j.geomorph.2023.108959>

2.  He K, Lombardo L, Chang L, **Sadhasivam N**, Hu X, Fang Z, & Tanyas H (2022) Investigating earthquake legacy effect on hillslope deformation using InSAR-derived time series. Earth Surface Processes and Landforms. DOI: <https://onlinelibrary.wiley.com/doi/epdf/10.1002/esp.5746>
:::

## 2022

::: {#2022}
1.  **Sadhasivam N**, Chang L, Tanyas H (2022) Revealing the hillslope response to earthquake legacy effect using time series InSAR. DOI: <https://doi.org/10.31223/X5DH22> \[preprint\]

2.  He K, Lombardo L, Chang L, **Sadhasivam N**, Hu X, Fang Z, & Tanyas H (2022) Hillslope recovery after a major earthquake: InSAR‑derived time series analyses to capture earthquake‑legacy effect. DOI: <https://doi.org/10.31223/X5Q65W> \[preprint\]

3.  Ahmad SM, **Sadhasivam N**, Lisa M, Lombardo L, Emil MK, Fadel I, van Westen CJ, Ahmed A. & Tanyas H (2022) Standing on the shoulder of a giant landslide: an InSAR look at a slow‑moving hillslope under melting glaciers in the western Karakoram. DOI: <https://doi.org/10.31223/X5P63T> \[preprint\]
:::

## 2021

::: {#2021}
1.  Pourghasemi HR, Honarmandnejad F, Rezaei M, Tarazkar MH & **Sadhasivam N** (2021) Prioritization of water erosion--prone sub‑watersheds using three ensemble methods in Qareaghaj catchment, southern Iran. Environmental Science and Pollution Research, 28(28), pp.37894‑37917. DOI: <https://doi.org/10.1007/s11356-021-13300-2>

2.  Pourghasemi HR, **Sadhasivam N**, Amiri M, Eskandari S & Santosh M (2021) Landslide susceptibility assessment and mapping using state‑of‑the art machine learning techniques. Natural Hazards, 108(1), pp.1291‑1316. DOI: <https://doi.org/10.1007/s11069-021-04732-7>

3.  Arabameri A, **Sadhasivam N**, Turabieh H, Mafarja M, Rezaie F, Pal SC & Santosh M (2021) Credal decision tree based novel ensemble models for spatial assessment of gully erosion and sustainable management. Scientific Reports, 11(1), pp.1‑18. DOI: <https://doi.org/10.1038/s41598-021-82527-3>
:::

## 2020

::: {#2020}
1.  Pourghasemi HR, Amiri M, Edalat M, Ahrari AH, Panahi M, **Sadhasivam N** & Lee S (2020) Assessment of urban infrastructures exposed to flood using susceptibility map and Google Earth Engine. IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing, 14, pp.1923‑1937. DOI: <https://doi.org/10.1109/JSTARS.2020.3045278>

2.  **Sadhasivam N,** Sheik Mohideen AR & Alankar B (2020) Optimisation of landfill sites for solid waste disposal in Thiruverumbur taluk of Tiruchirappalli district, India. Environmental Earth Sciences, 79(23), pp.1‑20. DOI: <https://doi.org/10.1007/s12665-020-09264-0>

3.  Pourghasemi HR, **Sadhasivam N**, Kariminejad N & Collins AL (2020) Gully erosion spatial modelling: Role of machine learning algorithms in selection of the best controlling factors and modelling process. Geoscience Frontiers, 11(6), pp.2207‑2219. DOI: <https://doi.org/10.1016/j.gsf.2020.03.005>

4.  Pourghasemi HR, Yousefi S, **Sadhasivam N** & Eskandari S (2020) Assessing, mapping, and optimizing the locations of sediment control check dams construction. Science of the Total Environment, 739, p.139954. DOI: <https://doi.org/10.1016/j.scitotenv.2020.139954>

5.  Eskandari S, Amiri M, **Sadhasivam N** & Pourghasemi HR (2020) Comparison of new individual and hybrid machine learning algorithms for modeling and mapping fire hazard: a supplementary analysis of fire hazard in different counties of Golestan Province in Iran. Natural Hazards, 104(1),

    pp.305‑327. DOI: <https://doi.org/10.1007/s11069-020-04169-4>

6.  Panahi M, **Sadhasivam N**, Pourghasemi HR, Rezaie F & Lee S (2020) Spatial prediction of groundwater potential mapping based on convolutional neural network (CNN) and support vector regression (SVR). Journal of Hydrology, 588, p.125033. DOI: <https://doi.org/10.1016/j.jhydrol.2020.125033>

7.  Pourghasemi HR, Pouyan S, Farajzadeh Z, **Sadhasivam N**, Heidari B, Babaei S & Tiefenbacher JP (2020) Assessment of the outbreak risk, mapping and infection behavior of COVID‑19: Application of the autoregressive integrated‑moving average (ARIMA) and polynomial models. Plos one, 15(7), p.e0236238. DOI: <https://doi.org/10.1371/journal.pone.0236238>

8.  **Sadhasivam N**, Bhardwaj A, Pourghasemi HR & Kamaraj NP (2020) Morphometric attributes‑based soil erosion susceptibility mapping in Dnyanganga watershed of India using individual and ensemble models. Environmental Earth Sciences, 79(14), pp.1‑28. DOI: <https://doi.org/10.1007/s12665-020-09102-3>

9.  Pourghasemi HR, **Sadhasivam N**, Yousefi S, Tavangar S, Nazarlou HG & Santosh M (2020) Using machine learning algorithms to map the groundwater recharge potential zones. Journal of environmental management, 265, p.110525. DOI: <https://doi.org/10.1016/j.jenvman.2020.110525>

10. Yousefi S, **Sadhasivam, N**, Pourghasemi HR, Nazarlou HG, Golkar F, Tavangar S & Santosh M (2020) Groundwater spring potential assessment using new ensemble data mining techniques. Measurement, 157, p.107652. DOI: <https://doi.org/10.1016/j.measurement.2020.107652>
:::

## 2019

::: {#2019}
1.  **Nitheshnirmal S**, Thilagaraj P, Rahaman S A, & Jegankumar R (2019). Erosion risk assessment through morphometric indices for prioritisation of Arjuna watershed using ALOS-PALSAR DEM. Modeling Earth Systems and Environment, *5*(3), pp. 907-924. DOI: <https://doi.org/10.1007/s40808-019-00578-y>

2.  Dineshkumar C, Kumar JS, **Sadhasivam N** (2019) Rice Monitoring Using Sentinel‑1 data in Google Earth Engine Platform. Proceedings of 2nd International Electronic Conference on Geosciences, 24(1), p.4. DOI: <https://doi.org/10.3390/IECG2019-06206>

3.  Dineshkumar C, **Sadhasivam N**, Bhardwaj A, Priyadarshini KN (2019) Phenological monitoring of paddy crop using time series MODIS data. Multidisciplinary Digital Publishing Institute Proceedings, 24(1). DOI: <https://doi.org/10.3390/IECG2019-06205>
:::
